
@baseUrl = http://localhost:8080
@contentType = application/json
@authorization = Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU0NTEzMjA5OWFkNmJmNjEzODJiNmI0Y2RlOWEyZGZlZDhjYjMwZjAiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoi6LaZ5bu65ZyLIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FwcGxlLWU5MTkxIiwiYXVkIjoiYXBwbGUtZTkxOTEiLCJhdXRoX3RpbWUiOjE3NjI0ODI5MzcsInVzZXJfaWQiOiIxMENhMDdTRFdPUW9mUVB4RkNUcWY3N3ZnR2IyIiwic3ViIjoiMTBDYTA3U0RXT1FvZlFQeEZDVHFmNzd2Z0diMiIsImlhdCI6MTc2MjQ4MjkzNywiZXhwIjoxNzYyNDg2NTM3LCJlbWFpbCI6InVzZXI2QGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInVzZXI2QGV4YW1wbGUuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.FD0Xae8NU0HIrjFJo_fJaPpo7kOH7ADDWZC3XesBremY8M9aH8fU8CJQMqRkAAE4_hKd5EImR6mrMePONEU8a4QsHZjMrR8bMkHSjJoLocWs8N2spPvcJT30Vgo4ciwQU2w_2VdJDxlq0O553qSUgjKBfgp8Pm1KqzXtTH-5cz_Im_jK91Wtk2bJ5nAa7n_7_Mn8LwGaB2E0BS9G4hs039a0lJI6WFi8cfp395K27TrWntpl_gocrOENWREZEuZ5PHp4DjCnp5nH12f3R6LXH8ojvcLWYiwQiPe2nb1KaNQu7vgYrGzJmuaMXKEKKgZpwXe1cE7i3f6zJEnALRks5A

### ============================================
### 登入取得 ID Token
### ============================================
POST {{baseUrl}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "apple21@example.com",
  "password": "qwer1234"
}

### ============================================
### 查看自己的訂單
### ============================================
GET {{baseUrl}}/api/orders
Content-Type: {{contentType}}
Authorization: {{authorization}}
###
GET {{baseUrl}}/api/orders?limit=4
Content-Type: {{contentType}}
Authorization: {{authorization}}
###
GET {{baseUrl}}/api/orders?limit=3&cursor=GpLAnlspHnvvqSKEi9Wi
Content-Type: {{contentType}}
Authorization: {{authorization}}

### ============================================
### 建立自己的訂單
### ============================================
POST {{baseUrl}}/api/orders
Content-Type: {{contentType}}
Authorization: {{authorization}}

{
  "items": [
    {
      "productId": "product111111",
      "productName": "測試商品",
      "quantity": 2,
      "price": 100
    },
    {
      "productId": "product222222",
      "productName": "測試商品2",
      "quantity": 1,
      "price": 222
    }
  ],
  "totalAmount": 322
}