
@baseUrl = http://localhost:8080
@contentType = application/json
@authorization = Bearer {_登入成功後取得token_}

### ============================================
### 登入取得 ID Token
### ============================================
POST {{baseUrl}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "apple21@example.com",
  "password": "qwer1234"
}

### ============================================
### 查看自己的訂單
### ============================================
GET {{baseUrl}}/api/orders
Content-Type: {{contentType}}
Authorization: {{authorization}}
###
GET {{baseUrl}}/api/orders?limit=4
Content-Type: {{contentType}}
Authorization: {{authorization}}
###
GET {{baseUrl}}/api/orders?limit=3&cursor=GpLAnlspHnvvqSKEi9Wi
Content-Type: {{contentType}}
Authorization: {{authorization}}

### ============================================
### 建立自己的訂單
### ============================================
POST {{baseUrl}}/api/orders
Content-Type: {{contentType}}
Authorization: {{authorization}}

{
  "items": [
    {
      "productId": "product111111",
      "productName": "測試商品",
      "quantity": 2,
      "price": 100
    },
    {
      "productId": "product222222",
      "productName": "測試商品2",
      "quantity": 1,
      "price": 222
    }
  ],
  "totalAmount": 322
}